version: '3'
services:
  mysql-db:
    image: mysql:5.6
    container_name: msql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankapp
    ports:
      - "3306:3306"
  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
